apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-acme-dev

resources:
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - superset-config.yaml
  - superset.yaml
  - ingress.yaml
  - bootstrap-job.yaml
