apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    import os
    SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY")

    CACHE_CONFIG = {
      "CACHE_TYPE": "RedisCache",
      "CACHE_DEFAULT_TIMEOUT": 300,
      "CACHE_KEY_PREFIX": "acme-dev:",
      "CACHE_REDIS_HOST": os.getenv("SUPERSET_REDIS_HOST", "redis"),
      "CACHE_REDIS_PORT": int(os.getenv("SUPERSET_REDIS_PORT", "6379")),
      "CACHE_REDIS_DB": int(os.getenv("SUPERSET_REDIS_DB", "0")),
    }
