apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: superset-tenants
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aniltyata/gitops.git
        revision: main
        directories:
          - path: clusters/prod/tenants/*/*
  template:
    metadata:
      name: "superset-{{path[3]}}-{{path[4]}}"
      labels:
        app: superset
        tenant: "{{path[3]}}"
        instance: "{{path[4]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/aniltyata/gitops.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "tenant-{{path[3]}}-{{path[4]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
